name: Deploy Frontend 

on:
  push:
    branches:
      - main  # Set your branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Execute SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 18
          cd /var/www/no-game.xyz/nogame-landing
          git fetch --all
          if ! git pull --ff-only; then
            echo "Conflicts detected. Resetting to origin/main..."
            git reset --hard origin/main
            git pull origin main
          fi
          npm install
          npm run build
          sudo systemctl reload nginx
